### ISSUE TITLE
yamllint enforcement broke

### ISSUE THREAD

**Issue by jamescassell** [MindPointGroup/RHEL7-STIG#185] opened 2018-10-19 19:52 UTC
A user opened a PR that had code style violations, and it passed CI.  Looks like this was broken by #169 and #170.

**Comment by defionscode** [comment] 2018-10-19 20:35
hmm it seems to have ran yamllint https://travis-ci.org/MindPointGroup/RHEL7-STIG/jobs/443871885#L715

**Comment by shepdelacreme** [comment] 2018-10-19 20:51
I'm looking at this now. It seems that molecule doesn't run yamllint against anything but the files in the molecule dir for some reason. It is probably due to my changes to the testing though.

**Comment by jamescassell** [comment] 2018-10-19 20:52
https://github.com/MindPointGroup/RHEL7-STIG/pull/170#pullrequestreview-166691737

**Comment by shepdelacreme** [comment] 2018-10-19 20:54
I see what the problem is working on another update to how the tests are laid out because molecule has some stupid behavior.

**Comment by shepdelacreme** [comment] 2018-10-22 17:02
Fixed in #187

**Closed by shepdelacreme** 2018-10-22 17:02 UTC
